name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy_infrastructure]
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    
    steps:
      - name: Checkout Infrastructure Repo
        uses: actions/checkout@v4

      # Download frontend artifact from frontend repository
      - name: Download Frontend Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GH_CROSS_REPO_TOKEN }}
          workflow: deploy.yml
          name: frontend-build
          path: ./frontend/dist
          repo: ${{ secrets.FRONTEND_REPO }}
          check_artifacts: true
          search_artifacts: true
          if_no_artifact_found: fail

      # Download backend artifact from backend repository
      - name: Download Backend Docker Image Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GH_CROSS_REPO_TOKEN }}
          workflow: deploy.yml
          name: bizinsight-backend-image
          path: bizinsight-backend.tar.gz
          repo: ${{ secrets.BACKEND_REPO }}
          check_artifacts: true
          search_artifacts: true
          if_no_artifact_found: fail

      # Create Firebase credentials file
      - name: Create Firebase Service Account File
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json

      # Archive frontend build for transfer
      - name: Archive Frontend Build
        run: tar -czf frontend-build.tar.gz -C frontend/dist .

      # Transfer files to server
      - name: Transfer Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.SERVER_IP }}
          username: ${{ vars.SERVER_USER }}
          key: |
            ${{ vars.SSH_PRIVATE_KEY }}
          source: "frontend-build.tar.gz,bizinsight-backend.tar.gz,firebase-service-account.json"
          target: "~/"
          strip_components: 0

      # Clean install infrastructure repo and deploy
      - name: Deploy on Remote Server
        uses: appleboy/ssh-action@v1.0.0
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        with:
          host: ${{ vars.SERVER_IP }}
          username: ${{ vars.SERVER_USER }}
          key: |
            ${{ vars.SSH_PRIVATE_KEY }}
          envs: OPENAI_API_KEY,JWT_SECRET_KEY
          script: |
            rm -rf ~/bizinsight-infrastructure
            rm -rf ~/bizinsight-backend
            rm -rf ~/bizinsight-frontend
            git clone https://${{ secrets.GH_CROSS_REPO_TOKEN }}@github.com/${{ github.repository }} ~/bizinsight-infrastructure
            git clone https://${{ secrets.GH_CROSS_REPO_TOKEN }}@github.com/${{ github.repository }} ~/bizinsight-backend
            mkdir -p ~/bizinsight-frontend
            cd ~/bizinsight-infrastructure
            chmod +x deploy.sh
            OPENAI_API_KEY="${OPENAI_API_KEY}" JWT_SECRET_KEY="${JWT_SECRET_KEY}" ./deploy.sh 